[[MicrosoftMPI]]
arch = "i686"
git-tree-sha1 = "af43ef978624af810badda189aadf8d069fa6d6a"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "c0910462cc474c897baff3cb4a2047601238c057feb6964de812c155c2346320"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.3+3/MicrosoftMPI.v10.1.3.i686-w64-mingw32.tar.gz"
[[MicrosoftMPI]]
arch = "x86_64"
git-tree-sha1 = "2accea874079246381f5016b827b40cf4973945a"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "09bda47e2956d59c73c35bd42c306adbb0eafcc6dc29535f9a9279476682e232"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.3+3/MicrosoftMPI.v10.1.3.x86_64-w64-mingw32.tar.gz"
