[[MicrosoftMPI]]
arch = "i686"
git-tree-sha1 = "7798fd2f53cf8a51cdad205c2e475a03286af00e"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "05257641036de0bb28077aedbdf0e9cad6e8425bb327eb248a7e459b0beb8051"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.2+4/MicrosoftMPI.v10.1.2.i686-w64-mingw32.tar.gz"
[[MicrosoftMPI]]
arch = "x86_64"
git-tree-sha1 = "4730d605ea54e3bebc45452bf4b3cf07caa25460"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "0beb7f56747a4a42b707de6ecb7d86bb2b75213bde6eeb718f771c3ff322027e"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.2+4/MicrosoftMPI.v10.1.2.x86_64-w64-mingw32.tar.gz"
