[[MicrosoftMPI]]
arch = "i686"
git-tree-sha1 = "4beafe0066fa90d0aa43bb2f609743ffd1d3b795"
libgfortran_version = "3.0.0"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "a7df1c88f0052afb616e4569040a9739cd0b54f6f4fe2c060933f3e2845abc21"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.4+0/MicrosoftMPI.v10.1.4.i686-w64-mingw32-libgfortran3.tar.gz"
[[MicrosoftMPI]]
arch = "i686"
git-tree-sha1 = "12634ac56d1fee99a045953ff2abc3c319cef6b1"
libgfortran_version = "4.0.0"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "cb8e24d689c79dbdd16873a1b4b98e7325d1d0c27e6c412f4167b127a3f26e8a"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.4+0/MicrosoftMPI.v10.1.4.i686-w64-mingw32-libgfortran4.tar.gz"
[[MicrosoftMPI]]
arch = "i686"
git-tree-sha1 = "8f9a46005101ab5da35f6e0fcf03dc193b82768a"
libgfortran_version = "5.0.0"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "9ce3572d4251d1e5bc61b8778c044ffd7750144f48a078e6e7f82d1865c56b8b"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.4+0/MicrosoftMPI.v10.1.4.i686-w64-mingw32-libgfortran5.tar.gz"
[[MicrosoftMPI]]
arch = "x86_64"
git-tree-sha1 = "aaaf8e4fe7c9510df417e366534fa2f84d6866f4"
libgfortran_version = "3.0.0"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "94c046d724738a11e02dfc091ed2ed3add1c6c0c4fe919f7df204c523bb42f2c"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.4+0/MicrosoftMPI.v10.1.4.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MicrosoftMPI]]
arch = "x86_64"
git-tree-sha1 = "7238fefe72e724fb32d067335ed26e6b080466a1"
libgfortran_version = "4.0.0"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "1907c11eea7dc18b6d44b17b8fd1e80d9f77c23ef8f7ae889082dfb1b1838e62"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.4+0/MicrosoftMPI.v10.1.4.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MicrosoftMPI]]
arch = "x86_64"
git-tree-sha1 = "454b73c5b1914776f73d2eae1b5c16c9a8bfc082"
libgfortran_version = "5.0.0"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "6b3cff1d2c53831f1f6c05a4ea9a866bc5c20101f49c51cae8c3de2dd23cbe17"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.4+0/MicrosoftMPI.v10.1.4.x86_64-w64-mingw32-libgfortran5.tar.gz"
