[[MicrosoftMPI]]
arch = "i686"
git-tree-sha1 = "ec08db795da4d126fc5c2ec479a6185687ac07f3"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "ba84b8a57cc37d4c3d872671e34ec9cd1b9f7ae5067c5cc8d99c45fdbcfd2c32"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.3+0/MicrosoftMPI.v10.1.3.i686-w64-mingw32.tar.gz"
[[MicrosoftMPI]]
arch = "x86_64"
git-tree-sha1 = "5c769ba3f01ccc862d4be99c785dbdae8ef7c8e6"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "5ccbfc2822d9e1d16649f71353a989d1268a05e92f9729e9c620fbf2af47efd2"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.3+0/MicrosoftMPI.v10.1.3.x86_64-w64-mingw32.tar.gz"
