[[MicrosoftMPI]]
arch = "i686"
git-tree-sha1 = "af43ef978624af810badda189aadf8d069fa6d6a"
libgfortran_version = "3.0.0"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "c0910462cc474c897baff3cb4a2047601238c057feb6964de812c155c2346320"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.3+4/MicrosoftMPI.v10.1.3.i686-w64-mingw32-libgfortran3.tar.gz"
[[MicrosoftMPI]]
arch = "i686"
git-tree-sha1 = "29289e2b991293b084804a388a8a48a932d28d27"
libgfortran_version = "4.0.0"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "f4a7dc46aa0581b9e1c033bedad5781323b7e8d24921e722869792f478b232e7"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.3+4/MicrosoftMPI.v10.1.3.i686-w64-mingw32-libgfortran4.tar.gz"
[[MicrosoftMPI]]
arch = "i686"
git-tree-sha1 = "622f785a3941796d105b2d2d66d9db6d2746757d"
libgfortran_version = "5.0.0"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "ef6a51640923f75f1e26c647ea2f51485bc11d5d6d8053c90dc94bcecc8f0754"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.3+4/MicrosoftMPI.v10.1.3.i686-w64-mingw32-libgfortran5.tar.gz"
[[MicrosoftMPI]]
arch = "x86_64"
git-tree-sha1 = "2accea874079246381f5016b827b40cf4973945a"
libgfortran_version = "3.0.0"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "09bda47e2956d59c73c35bd42c306adbb0eafcc6dc29535f9a9279476682e232"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.3+4/MicrosoftMPI.v10.1.3.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MicrosoftMPI]]
arch = "x86_64"
git-tree-sha1 = "c9eb201582137b9346aee34a02c55921867e863d"
libgfortran_version = "4.0.0"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "165201937a139774f6fa4658bc167eeae186135e6065332d9d00f717d419913f"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.3+4/MicrosoftMPI.v10.1.3.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MicrosoftMPI]]
arch = "x86_64"
git-tree-sha1 = "5ca446e8fa1c0c8ce2fd7c762d3c7883944de23a"
libgfortran_version = "5.0.0"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "c51f7aeab847bb1279530a217eb4c570198e94e9a86b8797c9ab2c3c87a8c5fa"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.3+4/MicrosoftMPI.v10.1.3.x86_64-w64-mingw32-libgfortran5.tar.gz"
