[[MicrosoftMPI]]
arch = "i686"
git-tree-sha1 = "09f0b59007bb528c40c86a6e1748f07dbb1fd9fb"
libgfortran_version = "3.0.0"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "d3cf6b3dc0721245e19bdcd5670aaaf3cfade5401934db49a7645653a39ce8d4"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.4+1/MicrosoftMPI.v10.1.4.i686-w64-mingw32-libgfortran3.tar.gz"
[[MicrosoftMPI]]
arch = "i686"
git-tree-sha1 = "698cf311be8c7935dc49201b16a226bb738a1297"
libgfortran_version = "4.0.0"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "c83506976481106826b9fdecf442b898b3318bd486d4c10392d094965b3957f2"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.4+1/MicrosoftMPI.v10.1.4.i686-w64-mingw32-libgfortran4.tar.gz"
[[MicrosoftMPI]]
arch = "i686"
git-tree-sha1 = "0e36bfc232d1a48c0c7f34eb9d86a5e23a180246"
libgfortran_version = "5.0.0"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "79b8662f1e631c6d1dbe6f9c3796dcc209de7833ea41b15d1f186acabad1635c"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.4+1/MicrosoftMPI.v10.1.4.i686-w64-mingw32-libgfortran5.tar.gz"
[[MicrosoftMPI]]
arch = "x86_64"
git-tree-sha1 = "063e92e909ef80fdb0c01da8cd38b2f117397020"
libgfortran_version = "3.0.0"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "6ec30873c011ec6ec9b91c0ec4394f3b3be088afc4dbcf234deb767d9ecff5f2"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.4+1/MicrosoftMPI.v10.1.4.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[MicrosoftMPI]]
arch = "x86_64"
git-tree-sha1 = "a927cc7394e1e0f0d1b8e0911c31d774c0b88b0c"
libgfortran_version = "4.0.0"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "301a51fc9757921f43d28544a725a8dcfe97bd94e3930e253d653cce60c1abda"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.4+1/MicrosoftMPI.v10.1.4.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[MicrosoftMPI]]
arch = "x86_64"
git-tree-sha1 = "4a195fc1f9aa324d571de9f2e6efdf6bb3562edf"
libgfortran_version = "5.0.0"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "3af20d8dbc13df8dca85e9673c9c46079da3f3ad9114e4f5ab2d711404bea142"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.4+1/MicrosoftMPI.v10.1.4.x86_64-w64-mingw32-libgfortran5.tar.gz"
