[[MicrosoftMPI]]
arch = "i686"
git-tree-sha1 = "5d69d2ec74dd8f76e3cca6393f947f5193524727"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "4e5d369b80ace93b3ecb2524dc51b4bd656ad600735271d2da222840fbf1570c"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.2+1/MicrosoftMPI.v10.1.2.i686-w64-mingw32.tar.gz"
[[MicrosoftMPI]]
arch = "x86_64"
git-tree-sha1 = "1085a12304e8930f31ef6e0d7124e669787c3309"
os = "windows"

    [[MicrosoftMPI.download]]
    sha256 = "bcbdb6c30068fcd4e89a1b1de45860ddc6e1b661dcc0ea68386f69e78402a739"
    url = "https://github.com/JuliaBinaryWrappers/MicrosoftMPI_jll.jl/releases/download/MicrosoftMPI-v10.1.2+1/MicrosoftMPI.v10.1.2.x86_64-w64-mingw32.tar.gz"
